--- #YAML:1.0
name: App-ErrorCalculator
version: 1.01
author:
  - Steffen Mueller <modules at steffen-mueller dot net>
abstract: Calculations with Gaussian Error Propagation
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
